<h1 align="center">Join Submission and Text Data Sets to Find Narrative Facts</h1>

### Import Code Libraries

In [1]:
import pandas as pd
import numpy as np

### Read Submissions and Text Data Sets for 2026 Q2 from [Mutual Fund Prospectus Risk/Return Summary Data Sets](https://www.sec.gov/data-research/sec-markets-data/mutual-fund-prospectus-riskreturn-summary-data-sets)

In [2]:
# Setting low_memory parameter to False to prevent mixed type inference and default_na parameter to False so that empty strings are not parsed as NaN.
submissions = pd.read_csv('data/2026q2_rr1/sub.tsv', sep='\t', low_memory=False, keep_default_na=False)
textFacts = pd.read_csv('data/2026q2_rr1/txt.tsv', sep='\t', low_memory=False, keep_default_na=False)

### Look at the Contents of submissions Data Frame

In [3]:
submissions

,adsh,cik,name,countryba,stprba,cityba,zipba,bas1,bas2,baph,...,changed,fye,pdate,effdate,form,filed,accepted,instance,nciks,aciks
0,0000009712-26-000040,9712,PRINCIPAL LIFE INSURANCE CO,US,IA,DES MOINES,50392-0300,711 HIGH STREET,,5152475111,...,19920929,,,,485BPOS,20260430,2026-04-29 20:41:00.0,psi-20260429_htm.xml,1,
1,0000009712-26-000044,9712,PRINCIPAL LIFE INSURANCE CO,US,IA,DES MOINES,50392-0300,711 HIGH STREET,,5152475111,...,19920929,,,,485BPOS,20260430,2026-04-29 20:42:00.0,pso-20260429_htm.xml,1,
2,0000009713-26-000157,9713,PRINCIPAL LIFE INSURANCE CO SEPARATE ACCOUNT B,US,IA,DES MOINES,50392,THE PRINCIPAL FINANCIAL GROUP,711 HIGH STREET,515-247-5461,...,20011016,1231,,,485BPOS,20260430,2026-04-29 19:37:00.0,ck0000009713-20260429_htm.xml,1,
3,0000009713-26-000178,9713,PRINCIPAL LIFE INSURANCE CO SEPARATE ACCOUNT B,US,IA,DES MOINES,50392,THE PRINCIPAL FINANCIAL GROUP,711 HIGH STREET,515-247-5461,...,20011016,1231,,,485BPOS,20260430,2026-04-29 19:53:00.0,ck0000009713-20260429_htm.xml,1,
4,0000012601-26-000240,12601,PRINCIPAL VARIABLE CONTRACTS FUNDS INC,US,IA,DES MOINES,50392,711 HIGH STREET,,515-247-5477,...,19980617,1231,20260501,,485BPOS,20260427,2026-04-27 14:20:00.0,ck0000012601-20260427_htm.xml,1,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2308,0002078265-26-000269,2078265,CORGI ETF TRUST I,US,DE,DOVER,19901,8 THE GREEN STE B,,5513302708,...,,1231,20260529,,497,20260618,2026-06-18 13:02:00.0,497c_htm.xml,1,
2309,0002078265-26-000282,2078265,CORGI ETF TRUST I,US,DE,DOVER,19901,8 THE GREEN STE B,,5513302708,...,,1231,20260605,,497,20260622,2026-06-22 12:14:00.0,cik0002078265-20260622_htm.xml,1,
2310,0002078265-26-000284,2078265,CORGI ETF TRUST I,US,DE,DOVER,19901,8 THE GREEN STE B,,5513302708,...,,1231,20260605,,497,20260622,2026-06-22 13:20:00.0,cik0002078265-20260622_htm.xml,1,
2311,0002078265-26-000295,2078265,CORGI ETF TRUST I,US,DE,DOVER,19901,8 THE GREEN STE B,,5513302708,...,,1231,20260605,,497,20260629,2026-06-29 16:59:00.0,497c_htm.xml,1,
2312,0002078265-26-000297,2078265,CORGI ETF TRUST I,US,DE,DOVER,19901,8 THE GREEN STE B,,5513302708,...,,1231,20260601,,497,20260630,2026-06-30 16:00:00.0,cik0002078265-20260630_htm.xml,1,

### Look at the Contents of textFacts Data Frame

In [4]:
textFacts

,adsh,tag,version,ddate,series,class,measure,document,otherdims,lang,iprx,dcml,dimn,escaped,srclen,txtlen,footnote,footlen,context,value
0,0001999371-26-008804,AmendmentFlag,dei/2025,20260430,,,,,,en-US,0,32767,0,0,5,5,,0,AsOf2026-04-23,false
1,0001999371-26-008804,DocumentType,dei/2025,20260430,,,,,,en-US,0,32767,0,0,7,7,,0,AsOf2026-04-23,485BPOS
2,0001999371-26-008804,EntityCentralIndexKey,dei/2025,20260430,,,,,,en-US,0,32767,0,0,10,10,,0,AsOf2026-04-23,0001121257
3,0001999371-26-008804,DocumentPeriodEndDate,dei/2025,20260430,,,,,,en-US,0,32767,0,0,10,10,,0,AsOf2026-04-23,2026-04-23
4,0001999371-26-008804,EntityInvCompanyType,dei/2025,20260430,,,,,,en-US,0,32767,0,0,4,4,,0,AsOf2026-04-23,N-1A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
638106,0002077810-26-000246,OperationOfBenefitTextBlock,vip/2026,20251231,,,,,Benefit=IndexLinkedVariableIncomeBenefitRisk;,en-US,0,32767,1,1,33627,15937,,0,c3,The built-in Benefit associated with the Annui...
638107,0002077810-26-000246,NameOfBenefitTextBlock,vip/2026,20251231,,,,,Benefit=IndexLinkedVariableIncomeBenefitRisk;,en-US,0,32767,1,0,36,36,,0,c3,Index Linked Variable Income Benefit
638108,0002077810-26-000246,BriefRestrictionsLimitationsTextBlock,vip/2026,20251231,,,,,Benefit=IndexLinkedVariableIncomeBenefitRisk;,en-US,0,32767,1,0,138,138,,0,c3,Income Withdrawals may not begin until the Inc...
638109,0002077810-26-000246,PrincipalRiskTextBlock,vip/2026,20251231,,,,,Risk=IndexLinkedVariableIncomeBenefitRisk;,en-US,0,32767,1,0,118,118,,0,c1,Index Linked Variable Income Benefit RiskYou c...
638110,0002078265-26-000297,RiskTextBlock,oef/2025,20260630,S000104044,,,,Risk=DepositaryReceiptsRisk;,en-US,0,32767,2,1,592,399,,0,P06_30_2026To06_30_2026_DepositaryReceiptsRisk...,Depositary Receipts Risk. The Fund may obtain...

### Merge submissions Data Frame with textFacts Data Frame Using adsh Column as a Join Key

In [5]:
mergedDF = pd.merge(submissions, textFacts, on='adsh')

### Look at the Contents of mergedDF Data Frame

In [6]:
mergedDF

,adsh,cik,name,countryba,stprba,cityba,zipba,bas1,bas2,baph,...,iprx,dcml,dimn,escaped,srclen,txtlen,footnote,footlen,context,value
0,0000009712-26-000040,9712,PRINCIPAL LIFE INSURANCE CO,US,IA,DES MOINES,50392-0300,711 HIGH STREET,,5152475111,...,0,32767,0,0,3,3,,0,c-5,N-4
1,0000009712-26-000040,9712,PRINCIPAL LIFE INSURANCE CO,US,IA,DES MOINES,50392-0300,711 HIGH STREET,,5152475111,...,0,32767,0,0,27,27,,0,c-5,PRINCIPAL LIFE INSURANCE CO
2,0000009712-26-000040,9712,PRINCIPAL LIFE INSURANCE CO,US,IA,DES MOINES,50392-0300,711 HIGH STREET,,5152475111,...,0,32767,0,0,10,10,,0,c-5,0000009712
3,0000009712-26-000040,9712,PRINCIPAL LIFE INSURANCE CO,US,IA,DES MOINES,50392-0300,711 HIGH STREET,,5152475111,...,0,32767,0,0,3,3,,0,c-5,N-4
4,0000009712-26-000040,9712,PRINCIPAL LIFE INSURANCE CO,US,IA,DES MOINES,50392-0300,711 HIGH STREET,,5152475111,...,0,32767,0,0,10,10,,0,c-5,2026-04-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
638106,0002078265-26-000297,2078265,CORGI ETF TRUST I,US,DE,DOVER,19901,8 THE GREEN STE B,,5513302708,...,0,32767,0,0,3,3,,0,P06_30_2026To06_30_2026,497
638107,0002078265-26-000297,2078265,CORGI ETF TRUST I,US,DE,DOVER,19901,8 THE GREEN STE B,,5513302708,...,0,32767,0,0,10,10,,0,P06_30_2026To06_30_2026,2026-06-30
638108,0002078265-26-000297,2078265,CORGI ETF TRUST I,US,DE,DOVER,19901,8 THE GREEN STE B,,5513302708,...,0,32767,0,0,10,10,,0,P06_30_2026To06_30_2026,2026-06-01
638109,0002078265-26-000297,2078265,CORGI ETF TRUST I,US,DE,DOVER,19901,8 THE GREEN STE B,,5513302708,...,0,32767,1,1,1258,903,,0,P06_30_2026To06_30_2026_S000104044MemberdeiLeg...,"Effective immediately, the Principal Investmen..."
638110,0002078265-26-000297,2078265,CORGI ETF TRUST I,US,DE,DOVER,19901,8 THE GREEN STE B,,5513302708,...,0,32767,2,1,592,399,,0,P06_30_2026To06_30_2026_DepositaryReceiptsRisk...,Depositary Receipts Risk. The Fund may obtain...

### Filter for Investment Strategy of STATE STREET INSTITUTIONAL INVESTMENT TRUST using StrategyNarrativeTextBlock tag

In [7]:
filter = (mergedDF.name == 'STATE STREET INSTITUTIONAL INVESTMENT TRUST') & (mergedDF.tag == 'StrategyNarrativeTextBlock') 
# create a data frame with a subset of columns
textFactsForStateStreet = mergedDF[filter][['name', 'series', 'document', 'tag', 'value']]
textFactsForStateStreet = textFactsForStateStreet.sort_values(by=['series', 'document'])
# reset the index of textFactsForStateStreet data frame
textFactsForStateStreet.reset_index(drop=True, inplace=True)
#left align the columns and headers
leftAlignedDF = textFactsForStateStreet.style.set_properties(**{'text-align': 'left', 'vertical-align':'top'})
leftAlignedDF.set_table_styles([dict(selector='th', props=[('text-align', 'left')])])

### Filter for Investment Risks of BLACKROCK FUNDS for using RiskTextBlock

In [8]:
filter = (mergedDF.name == 'BLACKROCK FUNDS') & (mergedDF.tag == 'RiskTextBlock') 
# create a data frame with a subset of columns
textFactsForBlackrock = mergedDF[filter][['name', 'series', 'document', 'tag', 'value']]
# reset the index of textFactsForBlackrock data frame
textFactsForBlackrock = textFactsForBlackrock.sort_values(by = ['series', 'document']).reset_index(drop=True)
#left align the columns and headers
leftAlignedDF = textFactsForBlackrock.style.set_properties(**{'text-align': 'left', 'vertical-align':'top'})
leftAlignedDF.set_table_styles([dict(selector='th', props=[('text-align', 'left')])])

### Create a Excel file for Risk Factors

In [9]:
# Save the Excel file in data folder
textFactsForBlackrock.to_excel('data/RiskFactors.xlsx', index=False)