<h1 align="center">Join Submissions, Numeric and Tags Data Sets to Find Custom Facts</h1>

### Import Code Libraries

In [1]:
import pandas as pd
import numpy as np
# Set the pandas column width to unlimited
pd.set_option('display.max_colwidth', None)

### Read Submissions, Numeric and Tags Data Sets for from [Mutual Fund Prospectus Risk/Return Summary Data Sets](https://www.sec.gov/data-research/sec-markets-data/mutual-fund-prospectus-riskreturn-summary-data-sets)

In [2]:
# Setting low_memory parameter to False to prevent mixed type inference and default_na parameter to False so that empty strings are not parsed as NaN.
submissions = pd.read_csv('data/2026q2_rr1/sub.tsv', sep='\t', low_memory=False, keep_default_na=False)
numericFacts = pd.read_csv('data/2026q2_rr1/num.tsv', sep='\t', low_memory=False, keep_default_na=False)
tags = pd.read_csv('data/2026q2_rr1/tag.tsv', sep='\t', low_memory=False, keep_default_na=False)

### Look at the Contents of submissions Data Frame

In [3]:
submissions

,adsh,cik,name,countryba,stprba,cityba,zipba,bas1,bas2,baph,...,changed,fye,pdate,effdate,form,filed,accepted,instance,nciks,aciks
0,0000009712-26-000040,9712,PRINCIPAL LIFE INSURANCE CO,US,IA,DES MOINES,50392-0300,711 HIGH STREET,,5152475111,...,19920929,,,,485BPOS,20260430,2026-04-29 20:41:00.0,psi-20260429_htm.xml,1,
1,0000009712-26-000044,9712,PRINCIPAL LIFE INSURANCE CO,US,IA,DES MOINES,50392-0300,711 HIGH STREET,,5152475111,...,19920929,,,,485BPOS,20260430,2026-04-29 20:42:00.0,pso-20260429_htm.xml,1,
2,0000009713-26-000157,9713,PRINCIPAL LIFE INSURANCE CO SEPARATE ACCOUNT B,US,IA,DES MOINES,50392,THE PRINCIPAL FINANCIAL GROUP,711 HIGH STREET,515-247-5461,...,20011016,1231,,,485BPOS,20260430,2026-04-29 19:37:00.0,ck0000009713-20260429_htm.xml,1,
3,0000009713-26-000178,9713,PRINCIPAL LIFE INSURANCE CO SEPARATE ACCOUNT B,US,IA,DES MOINES,50392,THE PRINCIPAL FINANCIAL GROUP,711 HIGH STREET,515-247-5461,...,20011016,1231,,,485BPOS,20260430,2026-04-29 19:53:00.0,ck0000009713-20260429_htm.xml,1,
4,0000012601-26-000240,12601,PRINCIPAL VARIABLE CONTRACTS FUNDS INC,US,IA,DES MOINES,50392,711 HIGH STREET,,515-247-5477,...,19980617,1231,20260501,,485BPOS,20260427,2026-04-27 14:20:00.0,ck0000012601-20260427_htm.xml,1,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2308,0002078265-26-000269,2078265,CORGI ETF TRUST I,US,DE,DOVER,19901,8 THE GREEN STE B,,5513302708,...,,1231,20260529,,497,20260618,2026-06-18 13:02:00.0,497c_htm.xml,1,
2309,0002078265-26-000282,2078265,CORGI ETF TRUST I,US,DE,DOVER,19901,8 THE GREEN STE B,,5513302708,...,,1231,20260605,,497,20260622,2026-06-22 12:14:00.0,cik0002078265-20260622_htm.xml,1,
2310,0002078265-26-000284,2078265,CORGI ETF TRUST I,US,DE,DOVER,19901,8 THE GREEN STE B,,5513302708,...,,1231,20260605,,497,20260622,2026-06-22 13:20:00.0,cik0002078265-20260622_htm.xml,1,
2311,0002078265-26-000295,2078265,CORGI ETF TRUST I,US,DE,DOVER,19901,8 THE GREEN STE B,,5513302708,...,,1231,20260605,,497,20260629,2026-06-29 16:59:00.0,497c_htm.xml,1,
2312,0002078265-26-000297,2078265,CORGI ETF TRUST I,US,DE,DOVER,19901,8 THE GREEN STE B,,5513302708,...,,1231,20260601,,497,20260630,2026-06-30 16:00:00.0,cik0002078265-20260630_htm.xml,1,

### Look at the Contents of numericFacts Data Frame

In [4]:
numericFacts

,adsh,tag,version,ddate,uom,series,class,measure,document,otherdims,iprx,value,footnote,footlen,dimn,dcml
0,0001133228-26-006519,AverageAnnualTotalReturns10YearsPercent,vip/2026,20251231,pure,,,,,Contract=SUNYORPLegacyPre11152021ContractAndNYSVDCLegacyPre11152021Contracts;PortfolioCompany=VanguardFTSESocialIndexFundInstitutionalShares;,0,0.1517,,0,2,4
1,0001133228-26-006519,AverageAnnualTotalReturns5YearsPercent,vip/2026,20251231,pure,,,,,Contract=SUNYORPLegacyPre11152021ContractAndNYSVDCLegacyPre11152021Contracts;PortfolioCompany=VanguardFTSESocialIndexFundInstitutionalShares;,0,0.1354,,0,2,4
2,0001133228-26-006519,AverageAnnualTotalReturns1YearPercent,vip/2026,20251231,pure,,,,,Contract=SUNYORPLegacyPre11152021ContractAndNYSVDCLegacyPre11152021Contracts;PortfolioCompany=VanguardFTSESocialIndexFundInstitutionalShares;,0,0.1731,,0,2,4
3,0001133228-26-006519,CurrentExpensesPercent,vip/2026,20251231,pure,,,,,Contract=SUNYORPLegacyPre11152021ContractAndNYSVDCLegacyPre11152021Contracts;PortfolioCompany=VanguardFTSESocialIndexFundInstitutionalShares;,0,0.0003,,0,2,4
4,0001133228-26-006521,AverageAnnualTotalReturns10YearsPercent,vip/2026,20251231,pure,,,,,Contract=SUNYORPLegacyPre11152021ContractAndNYSVDCLegacyPre11152021Contracts;PortfolioCompany=VanguardFTSESocialIndexFundInstitutionalShares;,0,0.1517,,0,2,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
537803,0002078265-26-000201,ExpenseExampleYear03,oef/2025,20260531,USD,S000104055,,,,Class=C000274653;,0,160.0000,,0,2,0
537804,0002078265-26-000201,ExpensesOverAssets,oef/2025,20260531,pure,S000104055,,,,Class=C000274653;,0,0.0050,"Under the unitary fee arrangement, Corgi Strategies, LLC (the ""Adviser""), or any sub-adviser it engages, will bear substantially all of the Fund's ordinary operating expenses, except for: advisory fees; interest on borrowings for investment purposes; dividends and other expenses on securities sold short; taxes; brokerage commissions and other costs of purchasing and selling portfolio securities and other investment instruments; acquired fund fees and expenses; accrued deferred tax liability; any distributio",715,2,4
537805,0002078265-26-000201,DistributionAndService12b1FeesOverAssets,oef/2025,20260531,pure,S000104055,,,,Class=C000274653;,0,0.0000,"Under the unitary fee arrangement, Corgi Strategies, LLC (the ""Adviser""), or any sub-adviser it engages, will bear substantially all of the Fund's ordinary operating expenses, except for: advisory fees; interest on borrowings for investment purposes; dividends and other expenses on securities sold short; taxes; brokerage commissions and other costs of purchasing and selling portfolio securities and other investment instruments; acquired fund fees and expenses; accrued deferred tax liability; any distributio",715,2,4
537806,0002078265-26-000201,ExpenseExampleYear01,oef/2025,20260531,USD,S000104055,,,,Class=C000274653;,0,51.0000,,0,2,0
537807,0002078265-26-000201,OtherExpensesOverAssets,oef/2025,20260531,pure,S000104055,,,,Class=C000274653;,0,0.0000,"Based on estimated amounts for the current fiscal year. | Under the unitary fee arrangement, Corgi Strategies, LLC (the ""Adviser""), or any sub-adviser it engages, will bear substantially all of the Fund's ordinary operating expenses, except for: advisory fees; interest on borrowings for investment purposes; dividends and other expenses on securities sold short; taxes; brokerage commissions and other costs of purchasing and selling portfolio securities and other investment instruments; acquired fund fees and",715,2,4

### Look at the Contents of tags Data Frame

In [5]:
tags

,tag,version,custom,abstract,datatype,iord,tlabel,doc
0,DistributionAndService12b1FeesOverAssets,oef/2024q3,0,0,nonNegativePure4,D,Distribution and Service (12b-1) Fees,
1,IndexLinkedOptionDetailsLowestLimitOnGainsPercent,vip/2026,0,0,percent,D,"Index-Linked Option Details, Lowest Limit on Gains [Percent]",
2,TradingSymbol,dei/2025,0,0,tradingSymbol,D,Trading Symbol,Trading symbol of an instrument as listed on an exchange.
3,ExpenseExampleByYearCaption,oef/2024q3,0,0,string,D,"Expense Example by, Year, Caption [Text]",
4,FixedOptionDetailsOtherMaterialFeaturesTextBlock,vip/2026,0,0,textBlock,D,"Fixed Option Details, Other Material Features [Text Block]",
...,...,...,...,...,...,...,...,...
1463,IndexLinkedOptionRiskMaximumLossResultingFromNegativeIndexPerformancePercent,vip/2026,0,0,percent,D,"Index-Linked Option Risk, Maximum Loss Resulting from Negative Index Performance [Percent]",
1464,AnnualReturn2018,vip/2025,0,0,percent,D,"Annual Return, 2018 [Percent]",
1465,IndexLinkedOptionOverviewCreditsAreBasedInPartOnIndexPerformanceTextBlock,vip/2025,0,0,textBlock,D,"Index-Linked Option Overview, Credits are Based in Part on Index Performance [Text Block]",
1466,FixedOptionDetailsMaturityNoticeFlag,vip/2025,0,0,boolean,D,"Fixed Option Details, Maturity Notice [Flag]",
1467,ShareholderFeesTableTextBlock,oef/2024q3,0,0,textBlock,D,Shareholder Fees [Table],

### Filter for Custom Monetary Tags

In [6]:
# use value of abstarct column as 0 to filter for concrete (non-abstract) tags
customTagsDF = tags[(tags.custom == 1) & (tags.abstract == 0) & (tags.datatype == 'monetary')]
customTagsDF

,tag,version,custom,abstract,datatype,iord,tlabel,doc
181,WireFee,0001213900-26-049224,1,0,monetary,D,Wire Fee,
435,RetirementAccountFees,0001213900-26-049224,1,0,monetary,D,Retirement Account Fees,
1293,OvernightCheckDeliveryFee,0001213900-26-049224,1,0,monetary,D,Overnight Check Delivery Fee,

### Merge submissions Data Frame with numericFacts Data Frame Using adsh Column as a Join Key

In [7]:
mergedSubmissionsAndNumericFactsDF = pd.merge(submissions, numericFacts, on='adsh')

### Merge mergedSubmissionsAndNumericFactsDF Data Frame with customTagsDF Data Frame Using adsh and tag as Join Keys

In [8]:
# Please note that version column = adsh for custom tags
mergedDF = pd.merge(mergedSubmissionsAndNumericFactsDF, customTagsDF, left_on=['adsh', 'tag'], right_on=['version', 'tag'])

### Look at the Contents of mergedDF Data Frame

In [9]:
mergedDF

,adsh,cik,name,countryba,stprba,cityba,zipba,bas1,bas2,baph,...,footlen,dimn,dcml,version_y,custom,abstract,datatype,iord,tlabel,doc
0,0001213900-26-049224,1318342,INVESTMENT MANAGERS SERIES TRUST,US,WI,MILWAUKEE,53212,235 WEST GALENA STREET,,626-914-4141,...,0,2,0,0001213900-26-049224,1,0,monetary,D,Wire Fee,
1,0001213900-26-049224,1318342,INVESTMENT MANAGERS SERIES TRUST,US,WI,MILWAUKEE,53212,235 WEST GALENA STREET,,626-914-4141,...,0,2,0,0001213900-26-049224,1,0,monetary,D,Wire Fee,
2,0001213900-26-049224,1318342,INVESTMENT MANAGERS SERIES TRUST,US,WI,MILWAUKEE,53212,235 WEST GALENA STREET,,626-914-4141,...,0,2,0,0001213900-26-049224,1,0,monetary,D,Wire Fee,
3,0001213900-26-049224,1318342,INVESTMENT MANAGERS SERIES TRUST,US,WI,MILWAUKEE,53212,235 WEST GALENA STREET,,626-914-4141,...,0,2,0,0001213900-26-049224,1,0,monetary,D,Wire Fee,
4,0001213900-26-049224,1318342,INVESTMENT MANAGERS SERIES TRUST,US,WI,MILWAUKEE,53212,235 WEST GALENA STREET,,626-914-4141,...,0,2,0,0001213900-26-049224,1,0,monetary,D,Wire Fee,
5,0001213900-26-049224,1318342,INVESTMENT MANAGERS SERIES TRUST,US,WI,MILWAUKEE,53212,235 WEST GALENA STREET,,626-914-4141,...,0,2,0,0001213900-26-049224,1,0,monetary,D,Wire Fee,
6,0001213900-26-049224,1318342,INVESTMENT MANAGERS SERIES TRUST,US,WI,MILWAUKEE,53212,235 WEST GALENA STREET,,626-914-4141,...,0,2,0,0001213900-26-049224,1,0,monetary,D,Wire Fee,
7,0001213900-26-049224,1318342,INVESTMENT MANAGERS SERIES TRUST,US,WI,MILWAUKEE,53212,235 WEST GALENA STREET,,626-914-4141,...,0,2,0,0001213900-26-049224,1,0,monetary,D,Wire Fee,
8,0001213900-26-049224,1318342,INVESTMENT MANAGERS SERIES TRUST,US,WI,MILWAUKEE,53212,235 WEST GALENA STREET,,626-914-4141,...,0,2,0,0001213900-26-049224,1,0,monetary,D,Wire Fee,
9,0001213900-26-049224,1318342,INVESTMENT MANAGERS SERIES TRUST,US,WI,MILWAUKEE,53212,235 WEST GALENA STREET,,626-914-4141,...,0,2,0,0001213900-26-049224,1,0,monetary,D,Wire Fee,
10,0001213900-26-049224,1318342,INVESTMENT MANAGERS SERIES TRUST,US,WI,MILWAUKEE,53212,235 WEST GALENA STREET,,626-914-4141,...,0,2,0,0001213900-26-049224,1,0,monetary,D,Wire Fee,
11,0001213900-26-049224,1318342,INVESTMENT MANAGERS SERIES TRUST,US,WI,MILWAUKEE,53212,235 WEST GALENA STREET,,626-914-4141,...,0,2,0,0001213900-26-049224,1,0,monetary,D,Wire Fee,
12,0001213900-26-049224,1318342,INVESTMENT MANAGERS SERIES TRUST,US,WI,MILWAUKEE,53212,235 WEST GALENA STREET,,626-914-4141,...,0,2,0,0001213900-26-049224,1,0,monetary,D,Retirement Account Fees,
13,0001213900-26-049224,1318342,INVESTMENT MANAGERS SERIES TRUST,US,WI,MILWAUKEE,53212,235 WEST GALENA STREET,,626-914-4141,...,0,2,0,0001213900-26-049224,1,0,monetary,D,Retirement Account Fees,
14,0001213900-26-049224,1318342,INVESTMENT MANAGERS SERIES TRUST,US,WI,MILWAUKEE,53212,235 WEST GALENA STREET,,626-914-4141,...,0,2,0,0001213900-26-049224,1,0,monetary,D,Retirement Account Fees,
15,0001213900-26-049224,1318342,INVESTMENT MANAGERS SERIES TRUST,US,WI,MILWAUKEE,53212,235 WEST GALENA STREET,,626-914-4141,...,0,2,0,0001213900-26-049224,1,0,monetary,D,Retirement Account Fees,
16,0001213900-26-049224,1318342,INVESTMENT MANAGERS SERIES TRUST,US,WI,MILWAUKEE,53212,235 WEST GALENA STREET,,626-914-4141,...,0,2,0,0001213900-26-049224,1,0,monetary,D,Retirement Account Fees,
17,0001213900-26-049224,1318342,INVESTMENT MANAGERS SERIES TRUST,US,WI,MILWAUKEE,53212,235 WEST GALENA STREET,,626-914-4141,...,0,2,0,0001213900-26-049224,1,0,monetary,D,Retirement Account Fees,
18,0001213900-26-049224,1318342,INVESTMENT MANAGERS SERIES TRUST,US,WI,MILWAUKEE,53212,235 WEST GALENA STREET,,626-914-4141,...,0,2,0,0001213900-26-049224,1,0,monetary,D,Retirement Account Fees,
19,0001213900-26-049224,1318342,INVESTMENT MANAGERS SERIES TRUST,US,WI,MILWAUKEE,53212,235 WEST GALENA STREET,,626-914-4141,...,0,2,0,0001213900-26-049224,1,0,monetary,D,Retirement Account Fees,
20,0001213900-26-049224,1318342,INVESTMENT MANAGERS SERIES TRUST,US,WI,MILWAUKEE,53212,235 WEST GALENA STREET,,626-914-4141,...,0,2,0,0001213900-26-049224,1,0,monetary,D,Retirement Account Fees,
21,0001213900-26-049224,1318342,INVESTMENT MANAGERS SERIES TRUST,US,WI,MILWAUKEE,53212,235 WEST GALENA STREET,,626-914-4141,...,0,2,0,0001213900-26-049224,1,0,monetary,D,Retirement Account Fees,
22,0001213900-26-049224,1318342,INVESTMENT MANAGERS SERIES TRUST,US,WI,MILWAUKEE,53212,235 WEST GALENA STREET,,626-914-4141,...,0,2,0,0001213900-26-049224,1,0,monetary,D,Retirement Account Fees,
23,0001213900-26-049224,1318342,INVESTMENT MANAGERS SERIES TRUST,US,WI,MILWAUKEE,53212,235 WEST GALENA STREET,,626-914-4141,...,0,2,0,0001213900-26-049224,1,0,monetary,D,Retirement Account Fees,
24,0001213900-26-049224,1318342,INVESTMENT MANAGERS SERIES TRUST,US,WI,MILWAUKEE,53212,235 WEST GALENA STREET,,626-914-4141,...,0,2,0,0001213900-26-049224,1,0,monetary,D,Overnight Check Delivery Fee,
25,0001213900-26-049224,1318342,INVESTMENT MANAGERS SERIES TRUST,US,WI,MILWAUKEE,53212,235 WEST GALENA STREET,,626-914-4141,...,0,2,0,0001213900-26-049224,1,0,monetary,D,Overnight Check Delivery Fee,
26,0001213900-26-049224,1318342,INVESTMENT MANAGERS SERIES TRUST,US,WI,MILWAUKEE,53212,235 WEST GALENA STREET,,626-914-4141,...,0,2,0,0001213900-26-049224,1,0,monetary,D,Overnight Check Delivery Fee,
27,0001213900-26-049224,1318342,INVESTMENT MANAGERS SERIES TRUST,US,WI,MILWAUKEE,53212,235 WEST GALENA STREET,,626-914-4141,...,0,2,0,0001213900-26-049224,1,0,monetary,D,Overnight Check Delivery Fee,
28,0001213900-26-049224,1318342,INVESTMENT MANAGERS SERIES TRUST,US,WI,MILWAUKEE,53212,235 WEST GALENA STREET,,626-914-4141,...,0,2,0,0001213900-26-049224,1,0,monetary,D,Overnight Check Delivery Fee,
29,0001213900-26-049224,1318342,INVESTMENT MANAGERS SERIES TRUST,US,WI,MILWAUKEE,53212,235 WEST GALENA STREET,,626-914-4141,...,0,2,0,0001213900-26-049224,1,0,monetary,D,Overnight Check Delivery Fee,
30,0001213900-26-049224,1318342,INVESTMENT MANAGERS SERIES TRUST,US,WI,MILWAUKEE,53212,235 WEST GALENA STREET,,626-914-4141,...,0,2,0,0001213900-26-049224,1,0,monetary,D,Overnight Check Delivery Fee,
31,0001213900-26-049224,1318342,INVESTMENT MANAGERS SERIES TRUST,US,WI,MILWAUKEE,53212,235 WEST GALENA STREET,,626-914-4141,...,0,2,0,0001213900-26-049224,1,0,monetary,D,Overnight Check Delivery Fee,
32,0001213900-26-049224,1318342,INVESTMENT MANAGERS SERIES TRUST,US,WI,MILWAUKEE,53212,235 WEST GALENA STREET,,626-914-4141,...,0,2,0,0001213900-26-049224,1,0,monetary,D,Overnight Check Delivery Fee,
33,0001213900-26-049224,1318342,INVESTMENT MANAGERS SERIES TRUST,US,WI,MILWAUKEE,53212,235 WEST GALENA STREET,,626-914-4141,...,0,2,0,0001213900-26-049224,1,0,monetary,D,Overnight Check Delivery Fee,
34,0001213900-26-049224,1318342,INVESTMENT MANAGERS SERIES TRUST,US,WI,MILWAUKEE,53212,235 WEST GALENA STREET,,626-914-4141,...,0,2,0,0001213900-26-049224,1,0,monetary,D,Overnight Check Delivery Fee,
35,0001213900-26-049224,1318342,INVESTMENT MANAGERS SERIES TRUST,US,WI,MILWAUKEE,53212,235 WEST GALENA STREET,,626-914-4141,...,0,2,0,0001213900-26-049224,1,0,monetary,D,Overnight Check Delivery Fee,

### Display a Subset of Columns for Custom Facts

In [10]:
customFacts = mergedDF[['name', 'series', 'otherdims', 'tag', 'dimn', 'ddate', 'uom', 'value']].sort_values(by= ['tag', 'series', 'otherdims'])
customFacts.reset_index(drop=True, inplace=True)
customFacts

,name,series,otherdims,tag,dimn,ddate,uom,value
0,INVESTMENT MANAGERS SERIES TRUST,S000046847,Class=C000146391;,OvernightCheckDeliveryFee,2,20251231,USD,25.0000
1,INVESTMENT MANAGERS SERIES TRUST,S000046847,Class=C000146392;,OvernightCheckDeliveryFee,2,20251231,USD,25.0000
2,INVESTMENT MANAGERS SERIES TRUST,S000046847,Class=C000146393;,OvernightCheckDeliveryFee,2,20251231,USD,25.0000
3,INVESTMENT MANAGERS SERIES TRUST,S000052270,Class=C000164379;,OvernightCheckDeliveryFee,2,20251231,USD,25.0000
4,INVESTMENT MANAGERS SERIES TRUST,S000052270,Class=C000164380;,OvernightCheckDeliveryFee,2,20251231,USD,25.0000
5,INVESTMENT MANAGERS SERIES TRUST,S000052270,Class=C000164381;,OvernightCheckDeliveryFee,2,20251231,USD,25.0000
6,INVESTMENT MANAGERS SERIES TRUST,S000052274,Class=C000164392;,OvernightCheckDeliveryFee,2,20251231,USD,25.0000
7,INVESTMENT MANAGERS SERIES TRUST,S000052274,Class=C000164393;,OvernightCheckDeliveryFee,2,20251231,USD,25.0000
8,INVESTMENT MANAGERS SERIES TRUST,S000052274,Class=C000164394;,OvernightCheckDeliveryFee,2,20251231,USD,25.0000
9,INVESTMENT MANAGERS SERIES TRUST,S000084477,Class=C000248863;,OvernightCheckDeliveryFee,2,20251231,USD,25.0000
10,INVESTMENT MANAGERS SERIES TRUST,S000084477,Class=C000248864;,OvernightCheckDeliveryFee,2,20251231,USD,25.0000
11,INVESTMENT MANAGERS SERIES TRUST,S000084477,Class=C000248865;,OvernightCheckDeliveryFee,2,20251231,USD,25.0000
12,INVESTMENT MANAGERS SERIES TRUST,S000046847,Class=C000146391;,RetirementAccountFees,2,20251231,USD,15.0000
13,INVESTMENT MANAGERS SERIES TRUST,S000046847,Class=C000146392;,RetirementAccountFees,2,20251231,USD,15.0000
14,INVESTMENT MANAGERS SERIES TRUST,S000046847,Class=C000146393;,RetirementAccountFees,2,20251231,USD,15.0000
15,INVESTMENT MANAGERS SERIES TRUST,S000052270,Class=C000164379;,RetirementAccountFees,2,20251231,USD,15.0000
16,INVESTMENT MANAGERS SERIES TRUST,S000052270,Class=C000164380;,RetirementAccountFees,2,20251231,USD,15.0000
17,INVESTMENT MANAGERS SERIES TRUST,S000052270,Class=C000164381;,RetirementAccountFees,2,20251231,USD,15.0000
18,INVESTMENT MANAGERS SERIES TRUST,S000052274,Class=C000164392;,RetirementAccountFees,2,20251231,USD,15.0000
19,INVESTMENT MANAGERS SERIES TRUST,S000052274,Class=C000164393;,RetirementAccountFees,2,20251231,USD,15.0000
20,INVESTMENT MANAGERS SERIES TRUST,S000052274,Class=C000164394;,RetirementAccountFees,2,20251231,USD,15.0000
21,INVESTMENT MANAGERS SERIES TRUST,S000084477,Class=C000248863;,RetirementAccountFees,2,20251231,USD,15.0000
22,INVESTMENT MANAGERS SERIES TRUST,S000084477,Class=C000248864;,RetirementAccountFees,2,20251231,USD,15.0000
23,INVESTMENT MANAGERS SERIES TRUST,S000084477,Class=C000248865;,RetirementAccountFees,2,20251231,USD,15.0000
24,INVESTMENT MANAGERS SERIES TRUST,S000046847,Class=C000146391;,WireFee,2,20251231,USD,20.0000
25,INVESTMENT MANAGERS SERIES TRUST,S000046847,Class=C000146392;,WireFee,2,20251231,USD,20.0000
26,INVESTMENT MANAGERS SERIES TRUST,S000046847,Class=C000146393;,WireFee,2,20251231,USD,20.0000
27,INVESTMENT MANAGERS SERIES TRUST,S000052270,Class=C000164379;,WireFee,2,20251231,USD,20.0000
28,INVESTMENT MANAGERS SERIES TRUST,S000052270,Class=C000164380;,WireFee,2,20251231,USD,20.0000
29,INVESTMENT MANAGERS SERIES TRUST,S000052270,Class=C000164381;,WireFee,2,20251231,USD,20.0000
30,INVESTMENT MANAGERS SERIES TRUST,S000052274,Class=C000164392;,WireFee,2,20251231,USD,20.0000
31,INVESTMENT MANAGERS SERIES TRUST,S000052274,Class=C000164393;,WireFee,2,20251231,USD,20.0000
32,INVESTMENT MANAGERS SERIES TRUST,S000052274,Class=C000164394;,WireFee,2,20251231,USD,20.0000
33,INVESTMENT MANAGERS SERIES TRUST,S000084477,Class=C000248863;,WireFee,2,20251231,USD,20.0000
34,INVESTMENT MANAGERS SERIES TRUST,S000084477,Class=C000248864;,WireFee,2,20251231,USD,20.0000
35,INVESTMENT MANAGERS SERIES TRUST,S000084477,Class=C000248865;,WireFee,2,20251231,USD,20.0000